autos=["Akura","Mazda","Honda","Toyota","Nissan"]
motos=["Ducati","Kawasaki","Harley Davidson","BMW","Italika"]
bicis=["Benotto","BMX","Apache","Mercurio","Trek"]
vehiculos=[autos,motos,bicis]
print(motos[2])
print("---------------------")
print(vehiculos[1][2])
print("---------------------")
print(vehiculos[2][4])
print("---------------------")
print(autos[1:4:1])
print("---------------------")
print(motos[3:0:-1])
print("---------------------")
print(motos[-2:-5:-1])
print("---------------------")
print(bicis[-1::-1])
print("---------------------")
print(bicis[::-1])
print("---------------------")
print(vehiculos[2][1:4:])
print("---------------------")
print(vehiculos[1::])
print("---------------------")
